name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AmericoEver
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update contribution snake'
          add: 'assets/*.svg'
